---
# maintains versions and can overwrite all.yml
near:
  validator:
    version: 2.10.1
    cli:
      general:
        version: v0.22.2
      validator:
        version: v0.1.8
    rust:
      version: 1.87.0
    rpc_url: https://rpc.mainnet.near.org
