$ANSIBLE_VAULT;1.1;AES256
32343362646161336331326563386630376561346663313162356635333430643036346130316632
6564396536666231363834346231623363623761303963610a383761656663393933616461323665
35653735623937386533313535623364333466346532663231303339643065393063653663333437
3432333838393336620a653934666333623934616335323632653736373561656636663634666235
32303537633763373233346162313362623161646633646165313566313832663435653138613664
63363566313434636136356162303031336433363438656335623235653230336362393466656439
62303865393134363938316535623262383032653265336264313739613735383665396263616533
36336364616663623861363932663536636464393639613136316131623732323264643330313462
35323435333033633639373661313930353661653836323637393737623763393636313738313830
36346361313866393131323965333137653932333038323234353666336332336161366530616265
34643265643565626135303463653761306632623934656339626336343535616263326462353434
35363135643138653336
